version: '3.8'

services:
  app:
    build: .
    container_name: bdu-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: sinhvien
      MONGODB_URI: mongodb://mongodb:27017/nest
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sinhvien
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

volumes:
  postgres_data:
